const CREATE_POST = "CREATE_POST";
const UPDATE_POST = "UPDATE_POST";
const UPDATE_LIKE = "UPDATE_LIKE";
const FETCH_POSTS = "FETCH_POST";
const DELETE_POST = "DELETE_POST";

const AUTH = "AUTH";
const GETJWT = "GETJWT";
const LOGOUT = "LOGOUT";

export {
  CREATE_POST,
  UPDATE_POST,
  UPDATE_LIKE,
  FETCH_POSTS,
  DELETE_POST,
  AUTH,
  GETJWT,
  LOGOUT,
};
