const START_LOADING = 'START_LOADING';
const END_LOADING = 'END_LOADING';

const CREATE_POST = 'CREATE_POST';
const UPDATE_POST = 'UPDATE_POST';
const UPDATE_LIKE = 'UPDATE_LIKE';
const ADD_COMMENT = 'ADD_COMMENT';
const FETCH_POSTS = 'FETCH_POSTS';
const FETCH_POST = 'FETCH_POST';
const FETCH_SEARCHPOSTS = 'FETCH_SEARCHPOSTS';
const DELETE_POST = 'DELETE_POST';

const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const CREATE_CART = 'CREATE_CART';
const ADDTO_CART = 'ADD_TO_CART';
const UPDATETO_CART = 'UPDATE_CART';
const REMOVEFROM_CART = 'REMOVEFROM_CART';
const EMPTY_CART = 'EMPTY_CART'
const REFRESH_CART = 'REFRESH_CART'
const CAPTURE_CHECKOUT = 'CAPTURE_CHECKOUT'
const CREATE_TOKEN = 'CREATE_TOKEN';
const AUTH = 'AUTH';
const GETJWT = 'GETJWT';
const LOGOUT = 'LOGOUT';

export {
	START_LOADING,
	END_LOADING,
	CREATE_POST,
	UPDATE_POST,
	UPDATE_LIKE,
  	ADD_COMMENT,
	FETCH_POSTS,
	FETCH_POST,
	FETCH_SEARCHPOSTS,
	DELETE_POST,

	FETCH_PRODUCTS,
	CREATE_CART,
	ADDTO_CART,
	UPDATETO_CART,
	REMOVEFROM_CART,
	EMPTY_CART,
	REFRESH_CART,
	CAPTURE_CHECKOUT,
	CREATE_TOKEN,

	AUTH,
	GETJWT,
	LOGOUT,
};
